In [1]:
import numpy as np


In [2]:
b=np.random.random((3,3))

In [3]:
c=np.random.random((3,3))

In [5]:
b

array([[0.87227083, 0.74974511, 0.14160162],
       [0.41995695, 0.48455187, 0.77442247],
       [0.57593997, 0.11681352, 0.30748523]])

In [6]:
c

array([[0.16666364, 0.77121158, 0.51949397],
       [0.27964072, 0.26520646, 0.55229192],
       [0.35385996, 0.05144898, 0.73199812]])

In [7]:
b + c

array([[1.03893446, 1.52095669, 0.66109558],
       [0.69959767, 0.74975833, 1.32671439],
       [0.92979993, 0.1682625 , 1.03948335]])

In [8]:
b -c

array([[ 0.70560719, -0.02146648, -0.37789235],
       [ 0.14031624,  0.21934541,  0.22213055],
       [ 0.22208001,  0.06536454, -0.42451288]])

In [9]:
b*c

array([[0.14537583, 0.57821211, 0.07356119],
       [0.11743706, 0.12850629, 0.42770727],
       [0.20380209, 0.00600994, 0.22507861]])

In [10]:
b/c

array([[5.23372012, 0.97216525, 0.27257606],
       [1.50177328, 1.82707414, 1.40219772],
       [1.62759293, 2.27047301, 0.42006287]])

In [11]:
b%c

array([[0.03895265, 0.74974511, 0.14160162],
       [0.14031624, 0.21934541, 0.22213055],
       [0.22208001, 0.01391556, 0.30748523]])

In [14]:
1/c

array([[229.57461416,   1.51424695,   3.59962011],
       [  3.82035462,   3.14640298,   1.43108735],
       [  1.37211786,  15.04030777,   7.59101653]])

In [12]:
2/b

array([[ 2.29286586,  2.66757327, 14.12413244],
       [ 4.76239286,  4.1275251 ,  2.58256969],
       [ 3.47258415, 17.12130625,  6.50437742]])

In [14]:
b += c #b=b+c

In [17]:
b

array([[1.2055981 , 2.29216828, 1.18058955],
       [0.97923839, 1.01496479, 1.87900631],
       [1.28365989, 0.21971147, 1.77148146]])

In [18]:
 b**2

array([[1.45346678, 5.2540354 , 1.39379169],
       [0.95890782, 1.03015353, 3.53066471],
       [1.64778271, 0.04827313, 3.13814657]])

In [21]:
0.52522541 *0.52522541

0.2758617313096681

In [19]:
1.45346678 * 1.45346678

2.1125656805635686