In [1]:
import numpy as np

In [5]:
arr=np.array([[34,456,78,987,23,34],[78,9,8,7,89,67]])

In [6]:
arr.T

array([[ 34,  78],
       [456,   9],
       [ 78,   8],
       [987,   7],
       [ 23,  89],
       [ 34,  67]])

In [36]:
arr=np.arange(40).reshape(4,10)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [25]:
arr=np.arange(40).reshape(4,5,2)

In [33]:
arr.transpose()

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33],
       [ 4, 14, 24, 34],
       [ 5, 15, 25, 35],
       [ 6, 16, 26, 36],
       [ 7, 17, 27, 37],
       [ 8, 18, 28, 38],
       [ 9, 19, 29, 39]])

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [28]:
arr.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39]]])